module.exports = {
  PRODUCT: 'product',
  PRODUCT_PROPERTY: 'product-property',
  RATING: 'rating',
  ORDER: 'order',
  ORDER_ITEM: 'order-item',
  CART_PRODUCT: 'cart-product',
  USER: 'user',
  USER_ROLE: 'user-role',
  ROLE: 'role',
  BRAND: 'brand',
  CATEGORY: 'category',
  CART: 'cart',
  REFRESH_TOKEN: 'refresh_token',

  BRAND_ID: 'brand_id',
  CATEGORY_ID: 'category_id',
  PRODUCT_ID: 'product_id',
  USER_ID: 'user_id',
  ORDER_ID: 'order_id',
  CART_ID: 'cart_id',
};
